//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class root {
    
    private string kindField;
    
    private byte totalItemsField;
    
    private rootItems[] itemsField;
    
    /// <remarks/>
    public string kind {
        get {
            return this.kindField;
        }
        set {
            this.kindField = value;
        }
    }
    
    /// <remarks/>
    public byte totalItems {
        get {
            return this.totalItemsField;
        }
        set {
            this.totalItemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("items")]
    public rootItems[] items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootItems {
    
    private string kindField;
    
    private string idField;
    
    private string etagField;
    
    private string selfLinkField;
    
    private rootItemsVolumeInfo volumeInfoField;
    
    private rootItemsSaleInfo saleInfoField;
    
    private rootItemsAccessInfo accessInfoField;
    
    private rootItemsSearchInfo searchInfoField;
    
    /// <remarks/>
    public string kind {
        get {
            return this.kindField;
        }
        set {
            this.kindField = value;
        }
    }
    
    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string etag {
        get {
            return this.etagField;
        }
        set {
            this.etagField = value;
        }
    }
    
    /// <remarks/>
    public string selfLink {
        get {
            return this.selfLinkField;
        }
        set {
            this.selfLinkField = value;
        }
    }
    
    /// <remarks/>
    public rootItemsVolumeInfo volumeInfo {
        get {
            return this.volumeInfoField;
        }
        set {
            this.volumeInfoField = value;
        }
    }
    
    /// <remarks/>
    public rootItemsSaleInfo saleInfo {
        get {
            return this.saleInfoField;
        }
        set {
            this.saleInfoField = value;
        }
    }
    
    /// <remarks/>
    public rootItemsAccessInfo accessInfo {
        get {
            return this.accessInfoField;
        }
        set {
            this.accessInfoField = value;
        }
    }
    
    /// <remarks/>
    public rootItemsSearchInfo searchInfo {
        get {
            return this.searchInfoField;
        }
        set {
            this.searchInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootItemsVolumeInfo {
    
    private string titleField;
    
    private string subtitleField;
    
    private string[] authorsField;
    
    private string publisherField;
    
    private string publishedDateField;
    
    private string descriptionField;
    
    private rootItemsVolumeInfoIndustryIdentifiers[] industryIdentifiersField;
    
    private rootItemsVolumeInfoReadingModes readingModesField;
    
    private ushort pageCountField;
    
    private bool pageCountFieldSpecified;
    
    private string printTypeField;
    
    private string categoriesField;
    
    private byte averageRatingField;
    
    private bool averageRatingFieldSpecified;
    
    private byte ratingsCountField;
    
    private bool ratingsCountFieldSpecified;
    
    private string maturityRatingField;
    
    private bool allowAnonLoggingField;
    
    private bool allowAnonLoggingFieldSpecified;
    
    private string contentVersionField;
    
    private rootItemsVolumeInfoPanelizationSummary panelizationSummaryField;
    
    private rootItemsVolumeInfoImageLinks imageLinksField;
    
    private string languageField;
    
    private string previewLinkField;
    
    private string infoLinkField;
    
    private string canonicalVolumeLinkField;
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string subtitle {
        get {
            return this.subtitleField;
        }
        set {
            this.subtitleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("authors")]
    public string[] authors {
        get {
            return this.authorsField;
        }
        set {
            this.authorsField = value;
        }
    }
    
    /// <remarks/>
    public string publisher {
        get {
            return this.publisherField;
        }
        set {
            this.publisherField = value;
        }
    }
    
    /// <remarks/>
    public string publishedDate {
        get {
            return this.publishedDateField;
        }
        set {
            this.publishedDateField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("industryIdentifiers")]
    public rootItemsVolumeInfoIndustryIdentifiers[] industryIdentifiers {
        get {
            return this.industryIdentifiersField;
        }
        set {
            this.industryIdentifiersField = value;
        }
    }
    
    /// <remarks/>
    public rootItemsVolumeInfoReadingModes readingModes {
        get {
            return this.readingModesField;
        }
        set {
            this.readingModesField = value;
        }
    }
    
    /// <remarks/>
    public ushort pageCount {
        get {
            return this.pageCountField;
        }
        set {
            this.pageCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pageCountSpecified {
        get {
            return this.pageCountFieldSpecified;
        }
        set {
            this.pageCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string printType {
        get {
            return this.printTypeField;
        }
        set {
            this.printTypeField = value;
        }
    }
    
    /// <remarks/>
    public string categories {
        get {
            return this.categoriesField;
        }
        set {
            this.categoriesField = value;
        }
    }
    
    /// <remarks/>
    public byte averageRating {
        get {
            return this.averageRatingField;
        }
        set {
            this.averageRatingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool averageRatingSpecified {
        get {
            return this.averageRatingFieldSpecified;
        }
        set {
            this.averageRatingFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ratingsCount {
        get {
            return this.ratingsCountField;
        }
        set {
            this.ratingsCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ratingsCountSpecified {
        get {
            return this.ratingsCountFieldSpecified;
        }
        set {
            this.ratingsCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string maturityRating {
        get {
            return this.maturityRatingField;
        }
        set {
            this.maturityRatingField = value;
        }
    }
    
    /// <remarks/>
    public bool allowAnonLogging {
        get {
            return this.allowAnonLoggingField;
        }
        set {
            this.allowAnonLoggingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool allowAnonLoggingSpecified {
        get {
            return this.allowAnonLoggingFieldSpecified;
        }
        set {
            this.allowAnonLoggingFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string contentVersion {
        get {
            return this.contentVersionField;
        }
        set {
            this.contentVersionField = value;
        }
    }
    
    /// <remarks/>
    public rootItemsVolumeInfoPanelizationSummary panelizationSummary {
        get {
            return this.panelizationSummaryField;
        }
        set {
            this.panelizationSummaryField = value;
        }
    }
    
    /// <remarks/>
    public rootItemsVolumeInfoImageLinks imageLinks {
        get {
            return this.imageLinksField;
        }
        set {
            this.imageLinksField = value;
        }
    }
    
    /// <remarks/>
    public string language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    public string previewLink {
        get {
            return this.previewLinkField;
        }
        set {
            this.previewLinkField = value;
        }
    }
    
    /// <remarks/>
    public string infoLink {
        get {
            return this.infoLinkField;
        }
        set {
            this.infoLinkField = value;
        }
    }
    
    /// <remarks/>
    public string canonicalVolumeLink {
        get {
            return this.canonicalVolumeLinkField;
        }
        set {
            this.canonicalVolumeLinkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootItemsVolumeInfoIndustryIdentifiers {
    
    private string typeField;
    
    private string identifierField;
    
    /// <remarks/>
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string identifier {
        get {
            return this.identifierField;
        }
        set {
            this.identifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootItemsVolumeInfoReadingModes {
    
    private bool textField;
    
    private bool imageField;
    
    /// <remarks/>
    public bool text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    public bool image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootItemsVolumeInfoPanelizationSummary {
    
    private bool containsEpubBubblesField;
    
    private bool containsImageBubblesField;
    
    /// <remarks/>
    public bool containsEpubBubbles {
        get {
            return this.containsEpubBubblesField;
        }
        set {
            this.containsEpubBubblesField = value;
        }
    }
    
    /// <remarks/>
    public bool containsImageBubbles {
        get {
            return this.containsImageBubblesField;
        }
        set {
            this.containsImageBubblesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootItemsVolumeInfoImageLinks {
    
    private string smallThumbnailField;
    
    private string thumbnailField;
    
    /// <remarks/>
    public string smallThumbnail {
        get {
            return this.smallThumbnailField;
        }
        set {
            this.smallThumbnailField = value;
        }
    }
    
    /// <remarks/>
    public string thumbnail {
        get {
            return this.thumbnailField;
        }
        set {
            this.thumbnailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootItemsSaleInfo {
    
    private string countryField;
    
    private string saleabilityField;
    
    private bool isEbookField;
    
    private rootItemsSaleInfoListPrice listPriceField;
    
    private rootItemsSaleInfoRetailPrice retailPriceField;
    
    private string buyLinkField;
    
    private rootItemsSaleInfoOffers offersField;
    
    /// <remarks/>
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public string saleability {
        get {
            return this.saleabilityField;
        }
        set {
            this.saleabilityField = value;
        }
    }
    
    /// <remarks/>
    public bool isEbook {
        get {
            return this.isEbookField;
        }
        set {
            this.isEbookField = value;
        }
    }
    
    /// <remarks/>
    public rootItemsSaleInfoListPrice listPrice {
        get {
            return this.listPriceField;
        }
        set {
            this.listPriceField = value;
        }
    }
    
    /// <remarks/>
    public rootItemsSaleInfoRetailPrice retailPrice {
        get {
            return this.retailPriceField;
        }
        set {
            this.retailPriceField = value;
        }
    }
    
    /// <remarks/>
    public string buyLink {
        get {
            return this.buyLinkField;
        }
        set {
            this.buyLinkField = value;
        }
    }
    
    /// <remarks/>
    public rootItemsSaleInfoOffers offers {
        get {
            return this.offersField;
        }
        set {
            this.offersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootItemsSaleInfoListPrice {
    
    private decimal amountField;
    
    private string currencyCodeField;
    
    /// <remarks/>
    public decimal amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    public string currencyCode {
        get {
            return this.currencyCodeField;
        }
        set {
            this.currencyCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootItemsSaleInfoRetailPrice {
    
    private decimal amountField;
    
    private string currencyCodeField;
    
    /// <remarks/>
    public decimal amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    public string currencyCode {
        get {
            return this.currencyCodeField;
        }
        set {
            this.currencyCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootItemsSaleInfoOffers {
    
    private byte finskyOfferTypeField;
    
    private rootItemsSaleInfoOffersListPrice listPriceField;
    
    private rootItemsSaleInfoOffersRetailPrice retailPriceField;
    
    /// <remarks/>
    public byte finskyOfferType {
        get {
            return this.finskyOfferTypeField;
        }
        set {
            this.finskyOfferTypeField = value;
        }
    }
    
    /// <remarks/>
    public rootItemsSaleInfoOffersListPrice listPrice {
        get {
            return this.listPriceField;
        }
        set {
            this.listPriceField = value;
        }
    }
    
    /// <remarks/>
    public rootItemsSaleInfoOffersRetailPrice retailPrice {
        get {
            return this.retailPriceField;
        }
        set {
            this.retailPriceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootItemsSaleInfoOffersListPrice {
    
    private uint amountInMicrosField;
    
    private string currencyCodeField;
    
    /// <remarks/>
    public uint amountInMicros {
        get {
            return this.amountInMicrosField;
        }
        set {
            this.amountInMicrosField = value;
        }
    }
    
    /// <remarks/>
    public string currencyCode {
        get {
            return this.currencyCodeField;
        }
        set {
            this.currencyCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootItemsSaleInfoOffersRetailPrice {
    
    private uint amountInMicrosField;
    
    private string currencyCodeField;
    
    /// <remarks/>
    public uint amountInMicros {
        get {
            return this.amountInMicrosField;
        }
        set {
            this.amountInMicrosField = value;
        }
    }
    
    /// <remarks/>
    public string currencyCode {
        get {
            return this.currencyCodeField;
        }
        set {
            this.currencyCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootItemsAccessInfo {
    
    private string countryField;
    
    private string viewabilityField;
    
    private bool embeddableField;
    
    private bool publicDomainField;
    
    private string textToSpeechPermissionField;
    
    private rootItemsAccessInfoEpub epubField;
    
    private rootItemsAccessInfoPdf pdfField;
    
    private string webReaderLinkField;
    
    private string accessViewStatusField;
    
    private bool quoteSharingAllowedField;
    
    /// <remarks/>
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public string viewability {
        get {
            return this.viewabilityField;
        }
        set {
            this.viewabilityField = value;
        }
    }
    
    /// <remarks/>
    public bool embeddable {
        get {
            return this.embeddableField;
        }
        set {
            this.embeddableField = value;
        }
    }
    
    /// <remarks/>
    public bool publicDomain {
        get {
            return this.publicDomainField;
        }
        set {
            this.publicDomainField = value;
        }
    }
    
    /// <remarks/>
    public string textToSpeechPermission {
        get {
            return this.textToSpeechPermissionField;
        }
        set {
            this.textToSpeechPermissionField = value;
        }
    }
    
    /// <remarks/>
    public rootItemsAccessInfoEpub epub {
        get {
            return this.epubField;
        }
        set {
            this.epubField = value;
        }
    }
    
    /// <remarks/>
    public rootItemsAccessInfoPdf pdf {
        get {
            return this.pdfField;
        }
        set {
            this.pdfField = value;
        }
    }
    
    /// <remarks/>
    public string webReaderLink {
        get {
            return this.webReaderLinkField;
        }
        set {
            this.webReaderLinkField = value;
        }
    }
    
    /// <remarks/>
    public string accessViewStatus {
        get {
            return this.accessViewStatusField;
        }
        set {
            this.accessViewStatusField = value;
        }
    }
    
    /// <remarks/>
    public bool quoteSharingAllowed {
        get {
            return this.quoteSharingAllowedField;
        }
        set {
            this.quoteSharingAllowedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootItemsAccessInfoEpub {
    
    private bool isAvailableField;
    
    private string acsTokenLinkField;
    
    /// <remarks/>
    public bool isAvailable {
        get {
            return this.isAvailableField;
        }
        set {
            this.isAvailableField = value;
        }
    }
    
    /// <remarks/>
    public string acsTokenLink {
        get {
            return this.acsTokenLinkField;
        }
        set {
            this.acsTokenLinkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootItemsAccessInfoPdf {
    
    private bool isAvailableField;
    
    private string acsTokenLinkField;
    
    /// <remarks/>
    public bool isAvailable {
        get {
            return this.isAvailableField;
        }
        set {
            this.isAvailableField = value;
        }
    }
    
    /// <remarks/>
    public string acsTokenLink {
        get {
            return this.acsTokenLinkField;
        }
        set {
            this.acsTokenLinkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootItemsSearchInfo {
    
    private string textSnippetField;
    
    /// <remarks/>
    public string textSnippet {
        get {
            return this.textSnippetField;
        }
        set {
            this.textSnippetField = value;
        }
    }
}
